
@startuml MasterMindPublicView_v1

title MasterMind - Public View

class MasterMind {
    -Board board
    -BreakerPlayer breakerPlayer
    +play()
    +exit()
}
class Board {
    -Combination secretCombination
    -Combination proposedCombination
    -void generateSecret()
    -boolean isWinner()
    +void setProposedCombination(ProposedCombination proposedCombination)
    +void printResult()
}

class BreakerPlayer {
    +ProposedCombination proposeCombination()
}

class Combination {
   -Color[4] positions 
   
}

class ProposedCombination {
    -int successBlackPosition
    -int successWhitePosition
    +void setSuccessPositions(Combination secret)
}

class SecretCombination

ProposedCombination --> SecretCombination

enum Color {
    Red
    Blue
    Yellow
    Green
    Orange
    Purple
}

MasterMind *--> Board
MasterMind *--> BreakerPlayer
Board *--> SecretCombination
Board o--> ProposedCombination
BreakerPlayer --> "1..10" Board : setProposedCombination
BreakerPlayer --> "10" ProposedCombination : return


Combination ^-- SecretCombination
Combination ^-- ProposedCombination
Combination *--> "4" Color

@enduml